name: Auto Accept Collabs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-accept-collabs@v1.0.0
        with:
          with:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

