name: Auto Accept Invitations

on:
  repository_invitation:
    types: [created]

jobs:
  accept_invite:
    runs-on: ubuntu-latest
    steps:
    - name: Accept the invitation
      run: |
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/user/repository_invitations/${{ github.event.invitation.id }}
