name: Auto Accept Invitations

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  accept_invites:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Accept Repository Invitations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch pending invitations
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/user/repository_invitations)

        # Loop through each invitation and accept it
        echo "$response" | jq -c '.[]' | while read -r invitation; do
          id=$(echo "$invitation" | jq '.id')
          echo "Accepting invitation ID: $id"
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/repository_invitations/$id
        done

